config/routes.rb
Rails.application.routes.draw do

  root 'gossip#index', as: '/home'

  get 'welcome/:welcome_user', to: 'welcome#welcome_user'

  get 'comments/:id/edit', to: 'comments#edit', as: 'edit/comment'
  post 'comments/create', to: 'comments#create'
  put 'comments/:id', to: 'comments#update', as: 'update/comment'
  delete 'comments/:id', to: 'comments#destroy', as: 'destroy/comment'

 
  resources :likes, only: [:create, :destroy]
  
  resources :sessions, only: [:new, :create, :destroy]

  resources :team

  resources :gossip

  resources :users

  resources :cities
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip

  validates :content, presence: true, length: { minimum: 1 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
include CommentsHelper
before_action :authenticate_user, only: [:create, :edit, :update, :destroy]
before_action :is_same_user, only: [:edit, :update, :destroy]
#########################################  
  def create
    @gossip = Gossip.find(params[:comment][:gossip_id])
    @comment = Comment.new(content: params[:comment][:content], user_id: current_user.id, gossip_id: @gossip.id)
    
    if @comment.save 
      puts "******* comment saved"
      redirect_to gossip_path(@gossip.id)
    else
      puts "******* mauvais comment"
      puts "Le comment n'as pu être crée pour la ou les raisons suivantes:"
      @comment.errors.full_messages.each do |message|
        puts "ERROR:  <>>>>  #{message}"
      end
      render gossip_path(@gossip.id)
    end
  end
#########################################
  def edit
    @comment = current_comment
    @gossip = @comment.gossip
  end

#########################################
  def update
    @comment = current_comment
    if @comment.update(content: params[:comment][:content])
      puts "******* comment update"
      redirect_to gossip_path(@comment.gossip_id)
    else
      puts "******* mauvais comment"
      puts "Le comment n'as pu être update pour la ou les raisons suivantes:"
      @comment.errors.full_messages.each do |message|
        puts "ERROR:  <>>>>  #{message}"
      end
      render edit_comment_path(@comment.id)
    end
  end

#########################################
  def destroy
      @comment = current_comment
      @gossip = Gossip.find(@comment.gossip_id)
      @comment.destroy
      redirect_to gossip_path(@gossip.id)
  end

#########################################

  private

########################################
  def authenticate_user
    unless current_user
      #flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

########################################
  def is_same_user
    if current_comment.user != current_user
      puts "Wrong user"
      redirect_to gossip_path(current_comment.gossip_id)
    end
  end
########################################

end

app/helpers/comments_helper.rb
module CommentsHelper
  def current_comment
    Comment.find(params[:id])
  end
end

app/views/comments/edit.html.erb
<div class="container-fluid bg-dark me-md-3 pt-3 px-3 pt-md-2 px-md-5 text-center overflow-hidden align-center">
<h1 class="display-5 text-white">Editer le Comment</h1>
<p>Auteur: <%= User.find(@comment.user_id).first_name %></p>
<p>Contenu: <%= @comment.content %></p>
<div class="container col-7">
    <%= form_with( url: update_comment_path(@comment.id), model: @comment, method: :put ) do |form| %>
        <div class="mb-3">
        <%= form.label :content, class: "form-label text-light" %>
        <%= form.text_field :content, class: "form-control" %>
        </div>
        <div class="mb-3">
        <%= form.submit "Modifier", class: "btn btn-warning" %>
        </div>
    <% end%>
    </div> 
<p>Supprimer le comment</p>
<p><%= link_to "Delete", destroy_comment_path(@comment.id), method: :delete, class: "btn btn-danger" %></p>
</div>