config/routes.rb
Rails.application.routes.draw do

  root 'gossip#index', as: '/home'

  get 'welcome/:welcome_user', to: 'welcome#welcome_user'

  get 'comments/:id/edit', to: 'comments#edit', as: 'edit/comment'
  post 'comments/create', to: 'comments#create'
  put 'comments/:id', to: 'comments#update', as: 'update/comment'
  delete 'comments/:id', to: 'comments#destroy', as: 'destroy/comment'

 
  resources :likes, only: [:create, :destroy]
  
  resources :sessions, only: [:new, :create, :destroy]

  resources :team

  resources :gossip

  resources :users

  resources :cities
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :users, through: :likes
  has_many :comments
  has_many :join_gossip_and_tags
  has_many :tags, through: :join_gossip_and_tags

  validates :title, presence: true, length: { minimum: 3}
  validates :content, presence: true
  validates :user_id, presence: true
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  include GossipHelper
  before_action :authenticate_user, only: [:new, :create, :edit, :update, :destroy, :show]
  before_action :is_same_user, only: [:edit, :update, :destroy]
########################################
  def index
    @gossips = Gossip.all
  end

########################################
  def show
    @gossip = current_gossip
    @like = Like.find_by(gossip_id: @gossip.id, user_id: current_user.id)
    @user = User.find(@gossip.user_id)
    @comments = Comment.where(gossip_id: @gossip.id)
    @comment = Comment.new
  end

########################################
  def new
      @gossip = Gossip.new
  end

########################################
  def create
      @gossip = Gossip.new(post_params)
      @gossip.user = current_user
      if @gossip.save 
        puts "******* gossip saved"
        redirect_to gossip_path(@gossip.id)
      else
          puts "******* mauvais gossip"
          puts "Le gosspip n'as pu être crée pour la ou les raisons suivantes:"
          @gossip.errors.full_messages.each do |message|
          puts "ERROR:  <>>>>  #{message}"
          end
        render new_gossip_path
      end
  end

########################################
  def edit
      @gossip = current_gossip
  end

########################################
  def update
      @gossip = current_gossip
      if @gossip.update(post_params)
        puts "******* gossip update"
        redirect_to gossip_path(@gossip.id)
      else
        puts "******* mauvais gossip"
        puts "Le gossip n'as pu être update pour la ou les raisons suivantes:"
        @gossip.errors.full_messages.each do |message|
          puts "ERROR:  <>>>>  #{message}"
        end
        render edit_gossip_path
      end
  end

########################################
  def destroy
    @gossip = current_gossip.destroy
    redirect_to gossip_index_path
  end

########################################
########################################

  private

########################################  
  def post_params
    params.require(:gossip).permit(:title, :content)
  end

######################################## 
  def authenticate_user
    unless current_user
      #flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

########################################
  def is_same_user
    if current_gossip.user != current_user
      puts "Wrong user"
      redirect_to gossip_path(params[:id])
    end
  end
######################################## 

end

app/helpers/gossip_helper.rb
module GossipHelper

  def current_gossip
    Gossip.find(params[:id])
  end
  
end

app/views/gossip/edit.html.erb
<div class="container-fluid bg-dark me-md-3 pt-3 px-3 pt-md-2 px-md-5 text-center overflow-hidden align-center">
<h1 class="display-5 text-white">Editer le Gossip: <% @gossip.title %></h1>
<div class="container col-7">
    <%= form_with( url: gossip_path(@gossip.id), model: @gossip, method: :put, local: true ) do |form| %>
        <div class="mb-3">
        <%= form.label :title, class: "form-label text-white" %>
        <%= form.text_field :title, class: "form-control" %>
        </div>
        <div class="mb-3">
        <%= form.label :content, class: "form-label text-light" %>
        <%= form.text_field :content, class: "form-control" %>
        </div>
        <div class="mb-3">
        <%= form.submit "Modifier", class: "btn btn-primary" %>
        </div>
    <% end%>
    </div> 
</div>

app/views/gossip/index.html.erb
<div class="p-5 mb-4 bg-light rounded-3">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Home</h1>
        <p class="col-md-8 fs-4">Ce site permet de créer des potins et de voir les potins des autres utilisateurs, alors créer toi un compte et rejoins la communauté Gossip</p>
      </div>
</div>
<div class="container-fluid bg-dark me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
  <h2 class="display-7 fw-bold">Home</h2>
  <div class="container-fluid">
    <% i = 0 %>
    <% i2 = 4 %>
    
    <div class="row">
        <% @gossips.each do |gossip| %>

          <div class="col-lg-3 bg-white border-left border-right mx-5 my-5 border-radius: 21px 21px 21px 21px;">
              <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"></rect><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>
              <h3>Titre : <%= gossip.title %></h3>
              <p>Ecrit part : <%= User.find(gossip.user_id.to_i).first_name %></p>
              <p>Nombre de commentaires : <%= Comment.where(gossip_id: gossip.id).count %></p>
              <p><%= link_to "Lien vers le Gossip", gossip_path(gossip.id), class: "btn btn-secondary" %></p>
              <% if current_user != nil %>
                <% like = Like.find_by(gossip_id: gossip.id, user_id: current_user.id)%>
                <% if like != nil %>
                  <p><%= link_to "Dislike", like_path(like.id), class: "btn btn-danger", method: :delete %></p>
                <% else %>
                  <p><%= link_to "Like", likes_path(gossip_id: gossip.id), class: "btn btn-primary", method: :post %></p>
                <% end %>
              <% else %>
                <p><%= link_to "Like", likes_path(gossip_id: gossip.id), class: "btn btn-primary", method: :post %></p>
              <% end %>
          </div>
          <% i2 += 1 %>
          <% i += 1 %>

          <% if i2 == 3 || i2 == 7 %>
            </div>
          <% end %>

          <% if i == 3 %>
            <div class="row">
            <% i = 0 %>
            <% i2 = 0 %>
          <% end %>

        <% end %>
        </div>

  </div>
</div>


app/views/gossip/new.html.erb
<div class="container-fluid bg-dark me-md-3 pt-3 px-3 pt-md-2 px-md-5 text-center overflow-hidden align-center">
  <h1 class="display-5 text-white">Créer un Gossip</h1>
    <div class="container col-7">
      <%= form_with( url: "/gossip", model: @gossip, method: :post, local: true ) do |form| %>
        <div class="mb-3">
        <%= form.label :title, class: "form-label text-white" %>
        <%= form.text_field :title, class: "form-control" %>
        </div>
        <div class="mb-3">
        <%= form.label :content, class: "form-label text-light" %>
        <%= form.text_field :content, class: "form-control" %>
        </div>
        <div class="mb-3">
        <%= form.submit "Créer", class: "btn btn-primary" %>
        </div>
      <% end%>
    </div> 
</div>

app/views/gossip/show.html.erb
<div class="container-fluid bg-dark me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 py-3 text-white">
        <h1 class="display-5">Gossip : <%= @gossip.title %></h1>
        <p class="lead">Ecrit part : <%= @user.first_name %></p>
        <p><%= link_to "Auteur", user_path(@user.id),class: "btn btn-primary" %>
        <%= link_to "Ville", city_path(City.find(@user.city_id).name), class: "btn btn-primary" %></p> 
        <p class="lead">Contenu :</p>
        <p><%= link_to "Editer", edit_gossip_path(@gossip.id), class: "btn btn-warning" %>
        <%= link_to "Détruire", gossip_path(@gossip.id), method: :delete, class: "btn btn-danger" %><p>
      </div>

      <div class="bg-light shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 21px 21px;">
        <p class="color-dark"><%= @gossip.content %> </p>
      </div>
      <div class="container py-3">
        <% if @like != nil %>
          <p><%= link_to "Dislike", like_path(@like.id), class: "btn btn-danger", method: :delete %></p>
        <% else %>
          <p><%= link_to "Like", likes_path(gossip_id: @gossip.id), class: "btn btn-primary", method: :post %></p>
        <% end %>
      </div>
</div>


<div class="container-fluid bg-dark me-md-3 pt-3 px-3 pt-md-2 px-md-5 text-center overflow-hidden align-center">
  <div class="my-3 py-3">
    <h2 class="display-5 text-white">Comments</h2>
    <% @comments.each do |comment|%>
      <div class="card d-inline-flex my-2 col-lg-7 border-radius: 21px 21px 21px 21px;">
        <div class="card-header">
          <p> Auteur : <%= User.find(comment.user_id).first_name %></p>
        </div>
        <div class="card-body">
          <p class="card-text"><%= comment.content %></p>
          <% if current_user == comment.user%>
          <p><%= link_to "Edit", edit_comment_path(comment.id), class: "btn btn-primary btn-sm" %></p>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>


<div class="container-fluid bg-dark me-md-3 pt-3 px-3 pt-md-2 px-md-5 text-center overflow-hidden align-center">
<h2 class="display-5 text-white">Create Comment</h2>
<div class="container col-7">
<%= form_with( url: comments_create_path, model: @comment, method: :post ) do |form| %>
    <%= form.hidden_field :gossip_id, value: params[:id] %>
    <div class="mb-3">
    <%= form.label :content, class: "form-label text-light" %>
    <%= form.text_field :content, class: "form-control" %>
    </div>
    <div class="mb-3">
    <%= form.submit "Commenter", class: "btn btn-primary" %>
    </div>
  <% end%>
  </div> 
</div>


  