config/routes.rb
Rails.application.routes.draw do

  root 'gossip#index', as: '/home'

  get 'welcome/:welcome_user', to: 'welcome#welcome_user'

  get 'comments/:id/edit', to: 'comments#edit', as: 'edit/comment'
  post 'comments/create', to: 'comments#create'
  put 'comments/:id', to: 'comments#update', as: 'update/comment'
  delete 'comments/:id', to: 'comments#destroy', as: 'destroy/comment'

 
  resources :likes, only: [:create, :destroy]
  
  resources :sessions, only: [:new, :create, :destroy]

  resources :team

  resources :gossip

  resources :users

  resources :cities
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_secure_password
  has_many :likes
  has_many :gossips, through: :likes
  has_many :gossips
  has_many :comments
  has_many :received_messages, foreign_key: 'recipient_id', class_name: 'PrivateMessage'
  has_many :sent_messages, foreign_key: 'sender_id', class_name: 'PrivateMessage'

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Donnez un mail valide" }
  validates :age, presence: true, numericality: { only_integer: true }
  validates :password, presence: true, length: { minimum: 6 }


#####################################
  def remember_it(remember_token)
    remember_digest = BCrypt::Password.create(remember_token)
    self.update(remember_digest: remember_digest)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
  end

  def show
    @user = User.find(params[:id])
    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
  end

  def new
    @user = User.new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  end

  def create
    if params[:user][:password] == params[:user][:password_confirm]
      @user = User.new(user_params)
      if @user.save
        log_in(@user)
        if params[:user][:stay_connect] == 1
          remember_him(@user)
        end
        puts "******* user saved and connected"
        redirect_to user_path(@user.id)
      else
        puts "******* mauvais user"
        puts "L'user n'as pu être créé(e) pour la ou les raisons suivantes:"
        @user.errors.full_messages.each do |message|
        puts "ERROR:  <>>>>  #{message}"
        end
        render new_user_path
      end
    end
  end

  def edit
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  end

  def update
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
  end

  def destroy
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :age, :email, :city_id, :password, :description)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="container-fluid bg-dark me-md-3 pt-3 px-3 pt-md-2 px-md-5 text-center overflow-hidden align-center">
  <h1 class="display-5 text-white">Créer un Compte</h1>
    <div class="container col-7">
      <%= form_with( url: users_path, model: @user, method: :post, local: true ) do |form| %>
        <div class="mb-3">
        <%= form.label :first_name, class: "form-label text-white" %>
        <%= form.text_field :first_name, class: "form-control" %>
        </div>
        
        <div class="mb-3">
        <%= form.label :last_name, class: "form-label text-white" %>
        <%= form.text_field :last_name, class: "form-control" %>
        </div>

        <div class="mb-3">
        <%= form.label :age, class: "form-label text-white" %>
        <%= form.text_field :age, class: "form-control" %>
        </div>

        <div class="mb-3">
        <%= form.label :email, class: "form-label text-white" %>
        <%= form.text_field :email, class: "form-control" %>
        </div>

        <div class="mb-3">
        <%= form.label :city_id, class: "form-label text-white" %>
        <%= form.text_field :city_id, class: "form-control" %>
        </div>

         <div class="mb-3">
        <%= form.label :password, class: "form-label text-white" %>
        <%= form.text_field :password, class: "form-control" %>
        </div>

         <div class="mb-3">
        <%= form.label :password_confirm, class: "form-label text-white" %>
        <%= form.text_field :password_confirm, class: "form-control" %>
        </div>

        <div class="mb-3">
        <%= form.label :description, class: "form-label text-light" %>
        <%= form.text_field :description, class: "form-control" %>
        </div>

        <div class="mb-3">
        <%= form.label :stay_connect, class: "form-label text-white" %>
        <%= form.check_box :stay_connect %>        
        </div>

        <div class="mb-3">
        <%= form.submit "Créer", class: "btn btn-primary" %>
        </div>
      <% end%>
    </div> 
</div>

app/views/users/show.html.erb
<div class="container-fluid bg-dark me-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 py-3 text-white">
        <h1 class="display-5">User : <%= @user.first_name %> <%= @user.last_name %></h1>
        <p class="lead">Age : <%= @user.age %></p>
        <p class="lead">eMail : <%= @user.email %></p>
        <p><%= link_to "Ville : #{City.find(@user.city_id).name}", city_path(City.find(@user.city_id).name), class: "btn btn-primary" %></p>
        <p class="lead">Description :</p>
      </div>
      <div class="bg-light shadow-sm mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 21px 21px;">
        <p class="color-dark"><%= @user.description %></p>
      </div>
      <div class="container">
        <h1 class="display-5">Ses Gossips</h1>
      </div>  
        <% Gossip.where(user_id: @user.id).each do |gossip| %>
          <div class="card d-inline-flex my-2 col-lg-7 border-radius: 21px 21px 21px 21px;">
            <div class="card-header">
              <p> Titre : <%= gossip.title %></p>
            </div>
            <div class="card-body">
              <p class="card-text"><%= gossip.content %></p>
              <p>Lien vers le gossip : <%= link_to gossip.title.to_s, gossip_path(gossip.id), class: 'btn btn-primary' %></p>
            </div>
          </div>
        <% end %>
      </div>
</div>