config/routes.rb
Rails.application.routes.draw do

  root 'gossip#index', as: '/home'

  get 'welcome/:welcome_user', to: 'welcome#welcome_user'

  get 'comments/:id/edit', to: 'comments#edit', as: 'edit/comment'
  post 'comments/create', to: 'comments#create'
  put 'comments/:id', to: 'comments#update', as: 'update/comment'
  delete 'comments/:id', to: 'comments#destroy', as: 'destroy/comment'

 
  resources :likes, only: [:create, :destroy]
  
  resources :sessions, only: [:new, :create, :destroy]

  resources :team

  resources :gossip

  resources :users

  resources :cities
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users

  validates :name, presence: true, uniqueness: true
  validates :zip_code, presence: true, length: { is: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip

  validates :content, presence: true, length: { minimum: 1 }
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :users, through: :likes
  has_many :comments
  has_many :join_gossip_and_tags
  has_many :tags, through: :join_gossip_and_tags

  validates :title, presence: true, length: { minimum: 3}
  validates :content, presence: true
  validates :user_id, presence: true
end

app/models/join_gossip_and_tag.rb
class JoinGossipAndTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :recipient, class_name: 'User'
  belongs_to :sender, class_name: 'User'

  validates :content, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_gossip_and_tags
  has_many :gossips, through: :join_gossip_and_tags

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_secure_password
  has_many :likes
  has_many :gossips, through: :likes
  has_many :gossips
  has_many :comments
  has_many :received_messages, foreign_key: 'recipient_id', class_name: 'PrivateMessage'
  has_many :sent_messages, foreign_key: 'sender_id', class_name: 'PrivateMessage'

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Donnez un mail valide" }
  validates :age, presence: true, numericality: { only_integer: true }
  validates :password, presence: true, length: { minimum: 6 }


#####################################
  def remember_it(remember_token)
    remember_digest = BCrypt::Password.create(remember_token)
    self.update(remember_digest: remember_digest)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def homepage
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def current_comment
    Comment.find(params[:id])
  end
end

app/helpers/gossip_helper.rb
module GossipHelper

  def current_gossip
    Gossip.find(params[:id])
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
###################################
  def current_user
    if session[:user_id]
      current_user = User.find_by(id: session[:user_id])
    elsif cookies[:user_id]
      user = User.find_by(id: cookies[:user_id])
      if user && BCrypt::Password.new(user.remember_digest).is_password?(cookies[:remember_token])
        log_in(user)
        current_user = user
      end
    end
  end
###################################
  def log_in(user)
    session[:user_id] = user.id
  end
###################################
  def logged_in?
    if session[:user_id] != nil
      return true
    else
      return false
    end  
  end

###################################
  def remember_him(user)
    # ici je vais créer un remember_token qui est une suite aléatoire de caractères
    remember_token = SecureRandom.urlsafe_base64
  
    # j'ai mon token, je vais stocker son digest en base de données :    
    user.remember_it(remember_token)
  
    #  maintenant, je vais créer les cookies : un cookie qui va conserver l'user_id, et un autre qui va enregistrer le remember_token
    cookies.permanent[:user_id] = user.id
    cookies.permanent[:remember_token] = remember_token
  
  end

###################################
  def forget(user)

    # on remet le remember_digest à nil puisqu'il ne nous servira plus :
    user.update(remember_digest: nil)
  
    # on efface les cookies dans le navigateur de l'utilisateur
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  
  end
  
###################################
  def log_out(user)
    session.delete(:user_id)
    forget(user)
  end

###################################
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><%= link_to "Home", home_path, class: "nav-link px-2 text-white" %></li>
          <li><%= link_to "New Gossip", new_gossip_path, class: "nav-link px-2 text-white" %></li>
          <li><%= link_to "Team", team_index_path, class: "nav-link px-2 text-white" %></li>
          <li><a href="#" class="nav-link px-2 text-white">About</a></li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
          <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
        </form>

        <div class="text-end">
          <% if session[:user_id] != nil %>
          <button type="button" class="btn btn-outline-light me-2"><%= link_to "Logout", session_path(session.id), method: :delete %></button>
          <% else %>
          <button type="button" class="btn btn-outline-light me-2"><%= link_to "Login", new_session_path %></button>
          <button type="button" class="btn btn-warning"><%= link_to "Sign Up", new_user_path %></button>
          <% end %>
        </div>
      </div>
    </div>
  </header>
  <%= yield %>
  </body>
</html>